name: Lint / Test / IT

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - name: Run Unit tests
        run: make test
      - name: Upload logs
        uses: actions/upload-artifact@v2
        with:
          name: test-logs
          path: test.log

  integration_test:
    name: Integration Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # https://docs.confluent.io/platform/current/installation/versions-interoperability.html
        kafka_version: [2.8.0, 2.7.0, 2.6.0, 2.5.0]
        include:
          - kafka_version: 2.8.0
            cp_version: 6.2.0
          - kafka_version: 2.7.0
            cp_version: 6.1.2
          - kafka_version: 2.6.0
            cp_version: 6.0.1
          - kafka_version: 2.5.0
            cp_version: 5.5.2
    env:
      CP_VERSION: ${{ matrix.cp_version }}
      KAFKAVERSION: ${{ matrix.kafka_version }}
      REQUESTTIMEOUT: 15s
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - name: Run integration tests
        run: make integration_test
      - name: Upload logs
        uses: actions/upload-artifact@v2
        with:
          name: it-logs
          path: integration-test.log
